services:
  app:
    image: lbadlani/spout-backend-aptos:v1 
    container_name: app
    ports:
      - "3000:3000"
    volumes:
      - /var/run/tappd.sock:/var/run/tappd.sock
    environment:
      - GRANT_SUDO=yes
      - NODE_ENV=production
      - PORT=3000
    user: root
    restart: always